server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${sky.datasource.driver-class-name}
      url: jdbc:mysql://${sky.datasource.host}:${sky.datasource.port}/${sky.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${sky.datasource.username}
      password: ${sky.datasource.password}
  redis:
    host: ${sky.redis.host}
    password: ${sky.redis.password}
    port: ${sky.redis.port}
    database: ${sky.redis.database}

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sky.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

sky:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    # 设置微信小程序登录令牌
    user-token-name: authentication
    user-secret-key: hjh
    user-ttl: 7200000
  #文件上传的基本参数(使用别的配置文件的引用)
  alioss:
    endpoint: ${sky.alioss.endpoint}
    bucket-name: ${sky.alioss.bucket-name}
    access-key-id: ${sky.alioss.access-key-id}
    access-key-secret: ${sky.alioss.access-key-secret}
  wechat:
    #微信小程序的appid和secret
    appid: ${sky.wechat.appid}
    secret: ${sky.wechat.secret}
    #微信支付相关参数
#    mchid: ${sky.wechat.mchid} #商户号
#    mchSerialNo: ${sky.wechat.mchSerialNo} #商户证书序列号
#    privateKeyFilePath: ${sky.wechat.privateKeyFilePath} #商户私钥文件
#    apiV3Key: ${sky.wechat.apiV3Key} #解密apiV3密钥
#    weChatPayCertFilePath: ${sky.wechat.weChatPayCertFilePath} #微信支付平台证书
#    notifyUrl: ${sky.wechat.notifyUrl} #微信支付回调地址，微信服务器返回给后端的支付结果
#    refundNotifyUrl: ${sky.wechat.refundNotifyUrl} #微信退款回调地址